language: node_js
node_js:
- 15
version: ~> 1.0
dist: xenial
os: linux
cache: npm
install:
  - npm install
script:
  - npm run test
deploy:
  provider: heroku
  app: ci-cd-travis-heroku
  api_key:
    secure: API_HEROKU
  on:
    branch: main