language: node_js
node_js:
- 15
version: "~> 1.0"
dist: xenial
os: linux
cache: npm
install:
- npm install
- heroku update
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: i5oVuCyE+ANauUG5zrHqJDK/kcnfWPhonWoHxQ7es28CiWrormW4N8N4GK4VXr83R5xWpoVaq1LI7E/ejhePPxBeyWU+NQJtkCjw5MkCxv/qZpH0K6PIkMdn1sYCCXW2+6Hfcn4eBiXdl8CbqVPtVqtm/mpVTAHsYoOo58C9oaDZ77Wx2LSlpNwM3wAYNr+9uS+PRO17WNIHExiChznN/1iiypa0EYF2grUFW+26i+na89mpKpR0qRp25koRdfyNK0e7LcrLrFynF4AbL69pgzgrEKOWh2MQePDkqUk0P/BkoQxo5qvMHpLUbJTBV7YbPDXPeZanOKomjoEvPWzg2u0/rgl/F0SHrjtoeRetsOQzoVKcWhPH6QIQKzouhcz22ZqxsG5Tt63k1MaXZY00r2EREJiX+EZM1OF5pQq8HfuQl++PX3fuXD576pnqeI3A2QzlYV9SPWAbzHsUyaBhyqFhFIO1eX8hfhp3VXEQvHY4hHyPF+vrYumHg8Tp41GaBeT9T5OmDbLqOrVGXzyEE4JlVIDgKtlIbTeMGB5GEyJ1vV981zLM00qKCrT/TzgmXpY0qc/hkkSWBWoq2FRKjIHotG5c6ncXN+NdRNvyI/MqylRw4XVBOTtgyBvFD0rA84lW2knBu359llvZfuJ8CJvqsq0g3LsDni3NKYsj9TA=
  on:
    branch:
    - main
