language: node_js
node_js:
- 15
version: "~> 1.0"
dist: xenial
os: linux
cache: npm
install:
- npm install
- heroku update
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: DTMIN8GDGx0x4W4RhcNqxvTdVeTAaTNEeiAypPWqLIE398BRj4hZWRb9kVHYbcma2rXtdbCGx1n3+F/t2clxFmSZq5jondoOppHyrMRxSBwkNB/xcrKxXK+dwnAso4IsK0w8VxTMpQYjbzHd0CZtxUFQhozRqYCUpg+YKALKnZdUbKwOTNSXw2jDjc5o3I6Nl6WzYj/yyCLlQpy4Bu2E4AKvMHdmc+fNSu8NrDiov8e++Blt/BqPpN385lmM3eG3KqcMOOfRWNinjaRFpH6ljJbxChQmUEakxQEL+kXQp6xAHN4MV/9hXYjcPYnqzOQ4XPcxxTPK2oBjEi3KCgV9o0gFpSejkm+oeUecpxjGrb4qaNbARY3fV+ocWKEb3Q0NnW3cLTXAhXkN1jKmLHaIFPx4lFDz8fhqCBYxAAar5HiMp9SU7CY4ycFdHpSgH0n5DHyILMmdswWxNq0fZecz6JNrd65I4u+kYmzaGlaXhF3YDhQlQnubrpGOFx6kPqMRDj3hpfhXQwNHHOguzPvnE5cPtfLQJFIAIujubuFWU0RO96Q0e+m2QBbwiE8p4GJUCAZKOTIkvWu8f14bYPwZsiD3VphMzKrrgyFaapAY1pdFteFZrI8z68hwEdJ/ZcsLljOzJJgSG+T1gqRSQatWC5qyfZheoCdzq0m44/LtQy0=
  on:
    branch:
    - main
