language: node_js
node_js:
- 15
version: "~> 1.0"
dist: xenial
os: linux
cache: npm
install:
- npm install
- heroku update
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: ZhTj/zOB3JBJuNp3nrscS9m3Hdz7oAabOpZQP62YseREt/1u+esSCfqOgARXWIhBUArOeE1Rsy/AK9u4HUS6zprGTv9s24TIsoiUdKuVVH4xsdQwMRae7oNq04iJWEubTlTej5es4t6V3iq08+awcDhKkB7U4owaqf4PbuCEz6ka60VQrznOEwll1BhI2kgx5pQMw21BZQhiuKQa32d5A2qIf0Mk1ln/fu/BPVteA2H6f3iflXJeNpp0N2AYqdu9/wG6eQ0fhqmPO6CWDUKpAGWTWPOIh7885+1EN9KVOvoYrP1Rr244f08TAyUWgsdi0BrGVVeNm6UtmleAB1jJGorFNFeyXK7kLmj/As6RjsjwAySj/ytVdRsx5MdV6mQ8lGu1acY734doC/DWLm1imXRe74YEBe8JYMlmcOql+uCAlEadvgz9CGf9ZWZzFCsGhGYms0gQJnG4rRCDk+dxgcK9B1YtH9jRA4c9EtFQbkVUc+3AYV55Mq7cJTpYFxfjsW6ujcKqWTZk7o0WxCnlzEdcR+gACYMFIyU8zXg70kCjdbik8PdP7jPsX4m4SV5jWakgRb2y+uyVj+40RzXTK7lXZv0bBDyMe6LRxo3y2KFCoMRDjEaWMIpx6wjxiWXksmV3z/G+He5VGJjfFl4hy9Gl1dojdn6Mk5OIdGgse88=
  on:
    branch:
      - main
