language: node_js
node_js:
- 15
version: ~> 1.0
dist: xenial
os: linux
cache: npm
install:
  - npm install
script:
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: 009c6622-c041-485f-85e9-5a07bf476a9f
  on:
    branch: main