language: node_js
node_js:
- 15
version: ~> 1.0
dist: xenial
os: linux
cache: npm
install:
  - npm install
script:
  - npm run test
env:
  - api=API_KEY_TOKEN
deploy:
  provider: heroku
  api_key:
    secure: api
  on:
    tags: on
    all_branches: true