language: node_js
node_js:
- 15
version: ~> 1.0
dist: xenial
os: linux
cache: npm
install:
  - npm install
script:
  - npm run test
env:
  - api=API_KEY_TOKEN
deploy:
  provider: heroku
  api_key: api
  app:
    master: ci-cd-heroku-travis
    production: ci-cd-heroku-travis