language: node_js
node_js:
- 11
version: ~> 1.0
dist: xenial
os: linux
cache: npm
install:
  - npm install
script:
  - npm run test
deploy:
  provider: heroku
  api_key: API_KEY_TOKEN
  app:
    master: ci-cd-heroku-travis
    production: ci-cd-heroku-travis