language: node_js
node_js:
- 15
version: "~> 1.0"
dist: xenial
os: linux
cache: npm
install:
- npm install
- heroku update
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: kDAFxUww47UmsJCZKFSGHibQ8d548sGd7fxGHLpYqmSwnt6Ua/hH9PGIw7qlXXdqAGZ/5ccWCfbZbrJdYlTDKgO9kYspBOkvDoIECcWVjBZVpAhKIIDPpT88bdCMUphKybhKNJTQft135ru7QVsAiZsclEYVFvVwgag6khSaEIjTqeCpg161ZoXicvU5xZr9aaCRV6rfl5I2IWyNNP/Qa9RRkNptx9g/mY0O4SGv6gDKHmVUPi+ZUjbxcuMybWRzhUrrNumHd8PPgMX+Zp1F36Z7px3VQPM8BqwwlSXlWaMvW8mBN63kU1R7VAts7PINqtH3dtH9lKhECMfQMkkzEBXYCkwjepmNffZtvhtFXUp7ogm2SThL/YxqpCuT0E1vBKmVQLMtxjyq1s/Ax2F3rKHGwU8/5ICNW1em+VF0IzhIzroE2Ow4KAtm0LfFmXpXRxvnz5MYPf4Fwg36gt3RP63DBXsxPv+2ITotsDpjTLuKFBe61Kk7dFZp3y0qN0ShfIxfjIikR9Zu0a7/T6NBxRbBNrJ4w1keCtcm/g2Eg7mtmqjtInoLQSyo62ORbvvNflVg9G8IPX/oOgQvSD2LK9QG7l4SMWzx1JNrjZhyITzPm7NtCG1NGieJr1ovvE3UcA1pun6K29rVDV/dQMS2WHrEKWeL9fX8uq7EnjC83hM=
  on:
    branch:
    - main
