language: node_js
node_js:
- 15
version: "~> 1.0"
dist: xenial
os: linux
cache: npm
install:
- npm install
- heroku update
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: OWqeUtwpfSLphuDC7AJxLFIOboJjSD+X2cEcE+eHGRpmGdVnANR7OmXr7gm08qzT9c6dJ9Exr92kxc6nACoX1Z7gqdeNf2U8Pl/gT8n5yFQyQNM4IrHNUY1LrEQumCT0gTK/Kfd+ARGOSQM/wdwYnKE77LErsVKpH+oAHSZXnWBJd2YudPu6lpNmaKr5FJwKU4vSpN6Q9DNYCD6LbqMXw6jkjeeMuiDn6X5E0iBh/k1zGs0akeWjgK2odQ+D1nxeVYmsdVkkB0mmbqGCghegbi2HT9ebX47th0349Tg44LLOybtiEFmIvnIjOUT5yZ3S2/3mTzsFwWNoCoxdaIwOCfROlbCdtG4vDbACGQQA1+Tsg7p+pomLfCMhzF8fAT4Xj1gd7g9nRmuNxBbxFPUg0p+ISTNbxgqMm8fZPMlgNGBaQnuP702TCS2rZJGw7NOEVuzo7DHXPly5uoA5YUlkhdrOjQjgzK4SmvO8ePFBmPfxjYF04vuE0QnRLaTqRmBrxV64Eo511EfJupb4Kqvz+YmCQ2GM8BGVnmTaeYSu8je8Ma+Q75/YxoMvaYlWOxo6I8+Q05jz2/iQqa/GaslNBxcyPlgkog87HAplnCYX/5LObrhWRqL2l4l1DwKeRU9gzYtW4fQKRTsw4/80GxHw3lPtAD1FPW82oxL/0r9z+ko=
  on:
    branch:
    - main
