language: node_js
node_js:
- 15
version: ~> 1.0
dist: xenial
os: linux
cache: npm
install:
  - npm install
script:
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: $API_KEY_TOKEN
  branch:
    only:
      - main